game: hypercorn app_game --reload --debug --bind app.local.gd:$PORT --access-logfile - --error-logfile - --log-level DEBUG
user: hypercorn app_users --reload --debug --bind app.local.gd:$PORT --access-logfile - --error-logfile - --log-level DEBUG
leaderboard: hypercorn app_leaderboard --reload --debug --bind app.local.gd:$PORT --access-logfile - --error-logfile - --log-level DEBUG

primary: ./bin/litefs -config ./etc/primary.yml 
secondary1: ./bin/litefs -config ./etc/secondary1.yml
secondary2: ./bin/litefs -config ./etc/secondary2.yml